import ast
from pathlib import Path

content = (
    'from __future__ import annotations\n'
    '\n'
    'import argparse\n'
    'import json\n'
    'import warnings\n'
    'from datetime import datetime, timezone\n'
    'from pathlib import Path\n'
    'from typing import Any, Dict, List\n'
    '\n'
    'import matplotlib.pyplot as plt\n'
    'import numpy as np\n'
    'import pandas as pd\n'
    'import seaborn as sns\n'
    'from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score\n'
    '\n'
    'warnings.filterwarnings("ignore", category=UserWarning, module="transformers")\n'
    '\n'
    '_LABEL_MAPS: Dict[str, Dict[str, str]] = {\n'
    '    "cardiffnlp/twitter-roberta-base-sentiment-latest": {\n'
    '        "label_0": "negative", "label_1": "neutral", "label_2": "positive",\n'
    '        "negative": "negative", "neutral": "neutral", "positive": "positive",\n'
    '    },\n'
    '    "ProsusAI/finbert": {"positive": "positive", "negative": "negative", "neutral": "neutral"},\n'
    '    "lxyuan/distilbert-base-multilingual-cased-sentiments-student": {\n'
    '        "positive": "positive", "negative": "negative", "neutral": "neutral",\n'
    '    },\n'
    '}\n'
    '\n'
    '_DISPLAY_NAMES: Dict[str, str] = {\n'
    '    "cardiffnlp/twitter-roberta-base-sentiment-latest": "RoBERTa-Twitter",\n'
    '    "ProsusAI/finbert": "FinBERT",\n'
    '    "lxyuan/distilbert-base-multilingual-cased-sentiments-student": "mDistilBERT",\n'
    '}\n'
    '\n'
    '\n'
    'def _find_latest_training_csv(explicit_path: str) -> Path:\n'
    '    if explicit_path:\n'
    '        path = Path(explicit_path)\n'
    '        if not path.exists():\n'
    '            raise FileNotFoundError(f"Training file not found: {path}")\n'
    '        return path\n'
    '    candidates = sorted(Path("data/preprocessed").glob("moltbook_training_ready_*.csv"))\n'
    '    if not candidates:\n'
    '        raise FileNotFoundError("No training CSV found. Run scripts/run_moltbook_polarity.py first.")\n'
    '    return candidates[-1]\n'
    '\n'
    '\n'
    'def _run_transformer(\n'
    '    texts: List[str], model_id: str, batch_size: int, max_length: int,\n'
    ') -> List[str]:\n'
    '    from transformers import pipeline as hf_pipeline\n'
    '    label_map = _LABEL_MAPS[model_id]\n'
    '    pipe = hf_pipeline(\n'
    '        task="text-classification", model=model_id, tokenizer=model_id,\n'
    '        truncation=True, max_length=max_length, batch_size=batch_size, device=-1,\n'
    '    )\n'
    '    predictions: List[str] = []\n'
    '    for res in pipe(texts, batch_size=batch_size):\n'
    '        raw = res["label"].lower().strip()\n'
    '        mapped = label_map.get(raw) or label_map.get(res["label"])\n'
    '        if mapped is None:\n'
    '            for key, val in label_map.items():\n'
    '                if key in raw:\n'
    '                    mapped = val\n'
    '                    break\n'
    '            mapped = mapped or "neutral"\n'
    '        predictions.append(mapped)\n'
    '    return predictions\n'
    '\n'
    '\n'
    'def _compute_metrics(\n'
    '    y_true: "pd.Series", y_pred: List[str], all_labels: List[str],\n'
    ') -> Dict[str, Any]:\n'
    '    report = classification_report(\n'
    '        y_true, y_pred, labels=all_labels, output_dict=True, zero_division=0\n'
    '    )\n'
    '    return {\n'
    '        "accuracy": float(accuracy_score(y_true, y_pred)),\n'
    '        "f1_macro": float(f1_score(y_true, y_pred, average="macro", zero_division=0)),\n'
    '        "labels": all_labels,\n'
    '        "confusion_matrix": confusion_matrix(y_true, y_pred, labels=all_labels).tolist(),\n'
    '        "classification_report": report,\n'
    '    }\n'
    '\n'
    '\n'
    'def _plot_metric_bars(metrics_by_model: Dict[str, Dict[str, Any]], out_path: Path) -> None:\n'
    '    names = list(metrics_by_model.keys())\n'
    '    acc = [metrics_by_model[n]["accuracy"] for n in names]\n'
    '    f1m = [metrics_by_model[n]["f1_macro"] for n in names]\n'
    '    x = np.arange(len(names))\n'
    '    w = 0.35\n'
    '    fig, ax = plt.subplots(figsize=(10, 6))\n'
    '    b1 = ax.bar(x - w / 2, acc, width=w, label="Accuracy", color="#4C72B0")\n'
    '    b2 = ax.bar(x + w / 2, f1m, width=w, label="Macro F1", color="#DD8452")\n'
    '    for bar in list(b1) + list(b2):\n'
    '        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.01,\n'
    '                f"{bar.get_height():.3f}", ha="center", va="bottom", fontsize=9)\n'
    '    ax.set_xticks(x)\n'
    '    ax.set_xticklabels(names, fontsize=11)\n'
    '    ax.set_ylim(0, 1.1)\n'
    '    ax.set_ylabel("Score", fontsize=12)\n'
    '    ax.set_title("Transformer Baselines: Accuracy vs Macro F1", fontsize=14)\n'
    '    ax.legend(fontsize=11)\n'
    '    ax.grid(axis="y", linestyle="--", alpha=0.4)\n'
    '    plt.tight_layout()\n'
    '    plt.savefig(out_path, dpi=180)\n'
    '    plt.close()\n'
    '\n'
    '\n'
    'def _plot_confusion_matrices(\n'
    '    metrics_by_model: Dict[str, Dict[str, Any]], labels: List[str], out_path: Path\n'
    ') -> None:\n'
    '    names = list(metrics_by_model.keys())\n'
    '    n = len(names)\n'
    '    fig, axes = plt.subplots(1, n, figsize=(6 * n, 5), squeeze=False)\n'
    '    for i, name in enumerate(names):\n'
    '        ax = axes[0, i]\n'
    '        cm = np.array(metrics_by_model[name]["confusion_matrix"])\n'
    '        sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",\n'
    '                    xticklabels=labels, yticklabels=labels, ax=ax)\n'
    '        ax.set_title(name, fontsize=12)\n'
    '        ax.set_xlabel("Predicted", fontsize=10)\n'
    '        ax.set_ylabel("True", fontsize=10)\n'
    '    plt.suptitle("Confusion Matrices - Transformer Baselines", fontsize=13, y=1.02)\n'
    '    plt.tight_layout()\n'
    '    plt.savefig(out_path, dpi=180, bbox_inches="tight")\n'
    '    plt.close()\n'
    '\n'
    '\n'
    'def _plot_classwise_f1(metrics_by_model: Dict[str, Dict[str, Any]], out_path: Path) -> None:\n'
    '    rows: List[Dict[str, Any]] = []\n'
    '    for name, m in metrics_by_model.items():\n'
    '        for lbl, vals in m.get("classification_report", {}).items():\n'
    '            if lbl in {"accuracy", "macro avg", "weighted avg"}:\n'
    '                continue\n'
    '            if isinstance(vals, dict) and "f1-score" in vals:\n'
    '                rows.append({"model": name, "label": lbl, "f1": vals["f1-score"]})\n'
    '    if not rows:\n'
    '        return\n'
    '    df = pd.DataFrame(rows)\n'
    '    plt.figure(figsize=(11, 6))\n'
    '    sns.barplot(data=df, x="label", y="f1", hue="model")\n'
    '    plt.ylim(0, 1)\n'
    '    plt.axhline(0.5, linestyle="--", color="grey", alpha=0.6, label="0.5 ref")\n'
    '    plt.title("Class-wise F1 - Transformer Baselines", fontsize=14)\n'
    '    plt.ylabel("F1 Score", fontsize=12)\n'
    '    plt.xlabel("Polarity Label", fontsize=12)\n'
    '    plt.legend(fontsize=10)\n'
    '    plt.tight_layout()\n'
    '    plt.savefig(out_path, dpi=180)\n'
    '    plt.close()\n'
    '\n'
    '\n'
    'def _plot_radar(\n'
    '    metrics_by_model: Dict[str, Dict[str, Any]], label_order: List[str], out_path: Path\n'
    ') -> None:\n'
    '    categories = label_order + ["macro_f1"]\n'
    '    n_cats = len(categories)\n'
    '    angles = np.linspace(0, 2 * np.pi, n_cats, endpoint=False).tolist()\n'
    '    angles += angles[:1]\n'
    '    fig, ax = plt.subplots(figsize=(8, 8), subplot_kw={"polar": True})\n'
    '    colors = ["#4C72B0", "#DD8452", "#55A868", "#C44E52"]\n'
    '    for color, (name, m) in zip(colors, metrics_by_model.items()):\n'
    '        rep = m["classification_report"]\n'
    '        vals = [rep.get(lbl, {}).get("f1-score", 0.0) for lbl in label_order]\n'
    '        vals.append(m["f1_macro"])\n'
    '        vals += vals[:1]\n'
    '        ax.plot(angles, vals, color=color, linewidth=2, label=name)\n'
    '        ax.fill(angles, vals, color=color, alpha=0.1)\n'
    '    ax.set_xticks(angles[:-1])\n'
    '    ax.set_xticklabels(categories, fontsize=11)\n'
    '    ax.set_ylim(0, 1)\n'
    '    ax.set_yticks([0.2, 0.4, 0.6, 0.8, 1.0])\n'
    '    ax.set_title("Radar - F1 per Class and Macro", fontsize=13, pad=18)\n'
    '    ax.legend(loc="upper right", bbox_to_anchor=(1.3, 1.1), fontsize=10)\n'
    '    plt.tight_layout()\n'
    '    plt.savefig(out_path, dpi=180, bbox_inches="tight")\n'
    '    plt.close()\n'
    '\n'
    '\n'
    'def main() -> None:\n'
    '    parser = argparse.ArgumentParser(\n'
    '        description="Evaluate pre-trained transformer models on MoltBook sentiment data."\n'
    '    )\n'
    '    parser.add_argument("--input", default="")\n'
    '    parser.add_argument("--label-col", default="processed_polarity_label")\n'
    '    parser.add_argument("--text-col", default="text_traditional_clean")\n'
    '    parser.add_argument("--batch-size", type=int, default=16)\n'
    '    parser.add_argument("--max-length", type=int, default=128)\n'
    '    parser.add_argument(\n'
    '        "--models", nargs="+", default=[\n'
    '            "cardiffnlp/twitter-roberta-base-sentiment-latest",\n'
    '            "ProsusAI/finbert",\n'
    '            "lxyuan/distilbert-base-multilingual-cased-sentiments-student",\n'
    '        ],\n'
    '    )\n'
    '    args = parser.parse_args()\n'
    '\n'
    '    if len(args.models) < 3:\n'
    '        raise ValueError("--models must specify at least three transformer model IDs.")\n'
    '\n'
    '    input_path = _find_latest_training_csv(args.input)\n'
    '    df = pd.read_csv(input_path)\n'
    '    for col in [args.text_col, args.label_col, "comment_id"]:\n'
    '        if col not in df.columns:\n'
    '            raise KeyError(f"Required column \'{col}\' not found.")\n'
    '\n'
    '    model_df = df[["comment_id", args.text_col, args.label_col]].dropna().copy()\n'
    '    model_df[args.text_col] = model_df[args.text_col].astype(str)\n'
    '    model_df[args.label_col] = model_df[args.label_col].astype(str)\n'
    '\n'
    '    texts = model_df[args.text_col].tolist()\n'
    '    y_true = model_df[args.label_col]\n'
    '    all_labels = sorted(y_true.unique().tolist())\n'
    '\n'
    '    print(f"\\nInput file : {input_path}")\n'
    '    print(f"Rows       : {len(model_df)}")\n'
    '    print(f"Labels     : {all_labels}")\n'
    '    print(f"Models     : {args.models}\\n")\n'
    '\n'
    '    preds_by_model: Dict[str, List[str]] = {}\n'
    '    metrics_by_model: Dict[str, Dict[str, Any]] = {}\n'
    '\n'
    '    for model_id in args.models:\n'
    '        display = _DISPLAY_NAMES.get(model_id, model_id.split("/")[-1])\n'
    '        print(f"  Running {display} ({model_id}) ...")\n'
    '        preds = _run_transformer(texts, model_id, args.batch_size, args.max_length)\n'
    '        m = _compute_metrics(y_true, preds, all_labels)\n'
    '        m["model_id"] = model_id\n'
    '        preds_by_model[display] = preds\n'
    '        metrics_by_model[display] = m\n'
    '        print(f"    accuracy={m[\'accuracy\']:.4f}  macro_f1={m[\'f1_macro\']:.4f}")\n'
    '\n'
    '    run_id = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")\n'
    '    out_dir = Path("data/modeling")\n'
    '    out_dir.mkdir(parents=True, exist_ok=True)\n'
    '\n'
    '    pred_df = pd.DataFrame({"comment_id": model_df["comment_id"].values, "y_true": y_true.values})\n'
    '    for name, preds in preds_by_model.items():\n'
    '        pred_df[f"pred_{name}"] = preds\n'
    '    pred_df["text"] = model_df[args.text_col].values\n'
    '    pred_path = out_dir / f"moltbook_transformer_predictions_{run_id}.csv"\n'
    '    pred_df.to_csv(pred_path, index=False, encoding="utf-8")\n'
    '\n'
    '    bar_path = out_dir / f"moltbook_transformer_metrics_bar_{run_id}.png"\n'
    '    cm_path  = out_dir / f"moltbook_transformer_confusion_matrices_{run_id}.png"\n'
    '    f1_path  = out_dir / f"moltbook_transformer_classwise_f1_{run_id}.png"\n'
    '    rad_path = out_dir / f"moltbook_transformer_radar_{run_id}.png"\n'
    '\n'
    '    _plot_metric_bars(metrics_by_model, bar_path)\n'
    '    _plot_confusion_matrices(metrics_by_model, all_labels, cm_path)\n'
    '    _plot_classwise_f1(metrics_by_model, f1_path)\n'
    '    _plot_radar(metrics_by_model, all_labels, rad_path)\n'
    '\n'
    '    summary = {\n'
    '        "run_id": run_id,\n'
    '        "input_path": str(input_path).replace("\\\\", "/"),\n'
    '        "rows_evaluated": int(len(model_df)),\n'
    '        "label_col": args.label_col,\n'
    '        "text_col": args.text_col,\n'
    '        "models_evaluated": args.models,\n'
    '        "metrics": metrics_by_model,\n'
    '        "predictions_path": str(pred_path).replace("\\\\", "/"),\n'
    '        "plots": {\n'
    '            "metrics_bar": str(bar_path).replace("\\\\", "/"),\n'
    '            "confusion_matrices": str(cm_path).replace("\\\\", "/"),\n'
    '            "classwise_f1": str(f1_path).replace("\\\\", "/"),\n'
    '            "radar": str(rad_path).replace("\\\\", "/"),\n'
    '        },\n'
    '    }\n'
    '    summary_path = out_dir / f"moltbook_transformer_summary_{run_id}.json"\n'
    '    summary_path.write_text(json.dumps(summary, indent=2, ensure_ascii=True), encoding="utf-8")\n'
    '\n'
    '    print("\\n" + "=" * 60)\n'
    '    print("Transformer Baseline Results")\n'
    '    print("=" * 60)\n'
    '    for name, m in metrics_by_model.items():\n'
    '        rep = m["classification_report"]\n'
    '        print(f"\\n  {name}")\n'
    '        print(f"    Accuracy : {m[\'accuracy\']:.4f}")\n'
    '        print(f"    Macro F1 : {m[\'f1_macro\']:.4f}")\n'
    '        for lbl in all_labels:\n'
    '            lv = rep.get(lbl, {})\n'
    '            print(\n'
    '                f"    [{lbl:9s}]  P={lv.get(\'precision\',0):.3f}"\n'
    '                f" R={lv.get(\'recall\',0):.3f}"\n'
    '                f" F1={lv.get(\'f1-score\',0):.3f}"\n'
    '                f" n={int(lv.get(\'support\',0))}"\n'
    '            )\n'
    '    print(f"\\n  predictions : {pred_path}")\n'
    '    print(f"  summary     : {summary_path}")\n'
    '    print(f"  plots       : {out_dir}")\n'
    '    print("=" * 60)\n'
    '\n'
    '\n'
    'if __name__ == "__main__":\n'
    '    main()\n'
)

target = Path('scripts/run_moltbook_modeling.py')
target.write_text(content, encoding='utf-8')
ast.parse(content)
print(f"Written {target} ({len(content.splitlines())} lines). Syntax OK.")
